### ISSUE TITLE
Incorrect tests for fToC

### ISSUE THREAD

**Issue by KurnosovNikita** [Shastel/temperature-converter#1]
All tests in **".fToC, should conver Fahrenheit to Celcius"** group call **cToF** instead of **fToC**.
Example:
```
it('Should convert 11° of Fahrenheit to -11.67° of Celcius', () => {
    const c = cToF(11);

    assert.equal(c, -11.67);
  });
```

**Comment by Shastel** [comment]
Fixed, [88aa977](https://github.com/Shastel/temperature-converter/commit/88aa977bde00676157ccb9848aab9b757a192419)
